#!/usr/bin/env node
// DevPilot frontend regression checks.
//
// Runs the real <script> from index.html in a stub DOM against payloads generated by the real backend
// (tests/make_fixtures.py, mocked providers only). Uses Node built-ins only; makes no network calls.
//
//   node tests/ui_check.js                 # generate fixtures, run every scenario
//   node tests/ui_check.js fixtures.json   # reuse an existing fixture file
'use strict';
const fs = require('fs'), os = require('os'), path = require('path'), vm = require('vm'), {execFileSync} = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const code = html.match(/<script>([\s\S]*)<\/script>/)[1];
let fixturePath = process.argv[2];
if (!fixturePath) {
  fixturePath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'devpilot-ui-')), 'fixtures.json');
  execFileSync('python3', [path.join(__dirname, 'make_fixtures.py'), fixturePath], {cwd: ROOT, stdio: ['ignore', 'ignore', 'pipe'], env: {...process.env, PYTHONDONTWRITEBYTECODE: '1'}});
}
const F = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));
const escH = s => String(s).replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
let failures = 0, total = 0;

function stubPage() {
  const els = {};
  const el = id => els[id] || (els[id] = (() => {
    const cls = new Set();
    return {id, innerHTML: '', textContent: '', value: 'o/r', disabled: false, dataset: {}, onclick: null, _cls: cls,
      classList: {add: c => cls.add(c), remove: c => cls.delete(c), toggle: (c, f) => ((f === undefined ? !cls.has(c) : f) ? cls.add(c) : cls.delete(c)), contains: c => cls.has(c)}};
  })());
  ['approval', 'results', 'council', 'finding', 'diff', 'issues', 'banner', 'loading'].forEach(id => el(id).classList.add('hidden'));
  return {els, el};
}

// routes: {path: [status, body] | (n, options, state) => [status, body] | Promise}. Any other request fails the scenario.
function run(name, routes, steps, checks) {
  return new Promise(resolve => {
    total++;
    const page = stubPage(), calls = [], state = {confirmDone: false, cancelled: false};
    const fetch = async (url, options) => {
      if (!url.startsWith('/api/')) throw Error('non-local request attempted: ' + url);
      const p = url.split('?')[0]; calls.push(p);
      const n = calls.filter(c => c === p).length, route = routes[p];
      if (!route) throw Error('unexpected request ' + p);
      const [status, body] = await (typeof route === 'function' ? route(n, options, state) : route);
      if (p === '/api/confirm') state.confirmDone = true;
      if (p === '/api/cancel') state.cancelled = true;
      if (status === 0) throw Error('network down');
      return {ok: status >= 200 && status < 300, status, json: async () => { if (body === 'NONJSON') throw SyntaxError('bad json'); return JSON.parse(JSON.stringify(body)); }};
    };
    const ctx = {document: {getElementById: page.el, addEventListener() {}}, fetch, console: {warn() {}}, setInterval: f => setInterval(f, 5), clearInterval,
      Date, JSON, String, Number, Array, Object, Math, Error, SyntaxError, encodeURIComponent, Promise, Boolean};
    vm.createContext(ctx);
    vm.runInContext(code + ';this.__t={S,execute,cancelPlan,start,renderResult,stopExpiry}', ctx);
    const t = ctx.__t, h = id => page.el(id).innerHTML, hidden = id => page.el(id)._cls.has('hidden');
    const stage = key => (h('stages').match(new RegExp(`data-stage="${key}" data-state="(\\w+)"`)) || [])[1];
    (async () => {
      for (const step of steps) { await step(t); await new Promise(r => setTimeout(r, 250)); }
      const problems = [];
      for (const [label, fn] of checks) {
        let ok;
        try { ok = fn({html: h, hidden, stage, t, calls, page}); } catch (e) { ok = 'threw ' + e.message; }
        if (ok !== true) problems.push(`${label}${ok === false ? '' : ': ' + ok}`);
      }
      t.stopExpiry(); clearInterval(t.S.poll); clearInterval(t.S.live);
      if (problems.length) failures++;
      console.log(`${problems.length ? 'FAIL' : 'PASS'} ${name}${problems.map(x => '\n     - ' + x).join('')}`);
      resolve();
    })();
  });
}

const R = name => F[name].result, ST = name => F[name].status;
const runningStatus = {status: 'running', terminal: false, result_ready: false, steps: [{step: 'Request', status: 'complete', detail: ''}, {step: 'GitHub Issue Search', status: 'complete', detail: ''}, {step: 'Security Reviewer', status: 'running', detail: ''}]};
const planned = name => ({'/api/plan': [200, {plan: R(name).plan}], '/api/execute': [202, {status: 'running', token: R(name).plan.token}]});
const polled = (name, extra = {}) => ({...planned(name), '/api/status': n => [200, n < 3 ? runningStatus : ST(name)], '/api/result': [200, R(name)], ...extra});
const afterConfirm = (before, after) => (n, o, st) => [200, st.confirmDone ? ST(after) : ST(before)];
const go = t => t.start();
const noSuccess = ({html}) => !/data-ok="true"/.test(html('results')) || 'success shown';
const approveButton = ({html}) => html('approval').includes('data-click="approve"');
const cancelButton = ({html}) => html('approval').includes('data-click="cancel"');

(async () => {
  const bulk = R('bulk').plan, ticket = bulk.jira_tickets[0], sp = bulk.slack_plan;
  await run('approval shows the saved ticket, blocked issues, and the exact Slack payload', polled('bulk'), [go], [
    ['polling stopped and idle', ({t}) => t.S.poll === null && !t.S.busy],
    ['approval visible', ({hidden}) => !hidden('approval')],
    ['exactly one ticket, for the reviewed target', ({html}) => bulk.jira_tickets.length === 1 && /data-ticket="0" data-reviewed="true"/.test(html('approval')) && !/data-ticket="1"/.test(html('approval'))],
    ['ticket summary exact', ({html}) => html('approval').includes(escH(ticket.body.fields.summary))],
    ['project shown', ({html}) => html('approval').includes('>KAN<')],
    ['blocked issue listed with reason', ({html}) => html('approval').includes('data-blocked-issue="2"') && html('approval').includes('Blocked · no ticket') && html('approval').includes(escH(bulk.blocked_jira_tickets[0].reason))],
    ['exact description shown', ({html}) => html('approval').includes(escH('Root cause: Hard-coded bypass token.'))],
    ['exact Slack text', ({html}) => html('approval').includes(`<pre class="text" data-slack-text>${escH(sp.text)}</pre>`)],
    ['Slack channel', ({html}) => html('approval').includes('#engineering')],
    ['dependency explained', ({html}) => html('approval').includes('Sent only if the Jira ticket is created') && html('approval').includes('withheld')],
    ['approve label exact', ({html}) => html('approval').includes('Approve 1 Jira ticket + 1 Slack message')],
    ['code approval separated', ({html}) => html('approval').includes('does <b>not</b> change any code')],
    ['expiry from the server shown', ({html}) => /Approval expires at .+ \(about 1[45] minutes left\)/.test(html('approval'))],
    ['cancel offered (server says cancellable)', cancelButton],
    ['awaiting approval stage blocked', ({stage}) => stage('approval') === 'blocked'],
    ['reviewers completed from status', ({stage}) => ['security', 'code', 'test'].every(k => stage(k) === 'complete')],
    ['jira not run yet', ({stage}) => stage('jira') === 'notrun'],
    ['no success claimed', noSuccess],
  ]);
  await run('approved run shows returned Jira key, link and Slack result', {...polled('bulk'), '/api/confirm': [200, R('bulk_final')], '/api/status': (n, o, st) => [200, st.confirmDone ? ST('bulk_final') : n < 3 ? runningStatus : ST('bulk')]},
    [go, t => t.execute(true)], [
    ['Jira key linked to configured site', ({html}) => html('results').includes('href="https://example.atlassian.net/browse/KAN-11"')],
    ['Slack sent shown', ({html}) => html('results').includes('Sent to #engineering')],
    ['one Jira success + slack', ({html}) => (html('results').match(/data-ok="true"/g) || []).length === 2],
    ['jira/slack stages complete', ({stage}) => stage('jira') === 'complete' && stage('slack') === 'complete' && stage('final') === 'complete'],
    ['approval hidden', ({hidden}) => hidden('approval')],
    ['approval stage shows approved', ({stage}) => stage('approval') === 'complete'],
    ['no error banner', ({hidden}) => hidden('banner')],
  ]);
  await run('Jira auth failure: error, reconnect guidance, Slack withheld', {...polled('jirafail'), '/api/confirm': [502, R('jirafail_final')], '/api/status': afterConfirm('jirafail', 'jirafail_final')},
    [go, t => t.execute(true)], [
    ['no success', noSuccess],
    ['auth guidance', ({html}) => html('results').includes('swytchcode auth connect jira')],
    ['slack withheld', ({html}) => html('results').includes('Slack notification withheld')],
    ['error banner', ({html, hidden}) => !hidden('banner') && html('banner').includes('no Jira issue was created')],
    ['jira stage failed, slack skipped', ({stage}) => stage('jira') === 'failed' && stage('slack') === 'skipped' && stage('final') === 'failed'],
  ]);
  await run('stale status response cannot overwrite newer state', {...polled('jirafail'),
      '/api/confirm': () => new Promise(r => setTimeout(() => r([502, R('jirafail_final')]), 40)),
      // requested while the confirm is in flight: answered late, with the older (pre-approval) status
      '/api/status': (n, o, st) => n === 1 ? [200, ST('jirafail')] : st.confirmDone ? [200, ST('jirafail_final')] : new Promise(r => setTimeout(() => r([200, ST('jirafail')]), 90))},
    [go, t => t.execute(true)], [
    ['final stages kept', ({stage}) => stage('jira') === 'failed' && stage('slack') === 'skipped'],
  ]);
  await run('bulk request: unreviewed issues are blocked, never ticketed', {...polled('bulk'), '/api/confirm': [200, R('bulk_final')], '/api/status': (n, o, st) => [200, st.confirmDone ? ST('bulk_final') : ST('bulk')]},
    [go, t => t.execute(true)], [
    ['only the reviewed issue got a ticket', ({html}) => (html('results').match(/Created .*? for GitHub #/g) || []).length === 1 && html('results').includes('for GitHub #1') && !html('results').includes('GitHub #2')],
    ['backend executed one ticket', () => R('bulk_final').actions.jira.length === 1 && R('bulk_final').actions.jira[0].issue_number === 1],
  ]);
  await run('review required: reviewer cards, evidence problems, no approval, no diff', polled('review_required'), [go], [
    ['three reviewer cards with returned decisions', ({html}) => /data-role="SECURITY" data-decision="REVIEW_REQUIRED"/.test(html('council')) && /data-role="CODE" data-decision="CONFIRMED"/.test(html('council')) && /data-role="TEST" data-decision="REVIEW_REQUIRED"/.test(html('council'))],
    ['code reviewer evidence problem', ({html}) => html('council').includes('src/login.py') && html('council').includes('Evidence problems')],
    ['council blocked', ({stage}) => stage('council') === 'blocked'],
    ['no approval', ({hidden}) => hidden('approval')],
    ['no finding', ({hidden}) => hidden('finding')],
    ['diff explains absence', ({html}) => html('diff').includes('did not confirm a finding') && !html('diff').includes('class="row')],
  ]);
  await run('insufficient evidence: reviewers not run, limitation shown', polled('insufficient'), [go], [
    ['reviewer cards say not run', ({html}) => (html('council').match(/data-decision="none"/g) || []).length === 3],
    ['reason shown', ({html}) => html('council').includes('content is incomplete')],
    ['reviewer stages not run', ({stage}) => stage('security') === 'notrun'],
    ['council stage marked', ({stage}) => ['skipped', 'blocked'].includes(stage('council'))],
    ['no approval', ({hidden}) => hidden('approval')],
  ]);
  await run('configuration error is terminal and explained', polled('config'), [go], [
    ['error banner', ({html}) => html('banner').includes('Jira project key')],
    ['no approval', ({hidden}) => hidden('approval')],
    ['idle', ({t}) => t.S.poll === null && !t.S.busy],
  ]);
  await run('proposal failure: fix unavailable, no approval', polled('proposal_fail'), [go], [
    ['diff unavailable shown', ({html}) => html('diff').includes('Proposed fix unavailable') && html('diff').includes('timed out')],
    ['finding stage failed', ({stage}) => stage('finding') === 'failed'],
    ['no approval', ({hidden}) => hidden('approval')],
  ]);
  await run('reviewer failure: requested writes are reported as not planned, not as unrequested', polled('reviewer_fail'), [go], [
    ['error names the schema problem', ({html}) => html('banner').includes("reviewer must be &#39;CODE&#39;, got &#39;SECURITY&#39;")],
    ['approval stage explains why', ({html}) => html('stages').includes('Jira and Slack were requested but not planned: the run ended with an error before approval.')],
    ['old misleading text gone', ({html}) => !html('stages').includes('No supported Jira or Slack action was requested')],
    ['code reviewer stage failed', ({stage}) => stage('code') === 'failed'],
    ['test reviewer never ran', ({stage}) => stage('test') === 'notrun'],
    ['no approval', ({hidden}) => hidden('approval')],
    ['no success', noSuccess],
  ]);
  await run('blocked run: only an accurate run-status preview, no ticket', {...polled('status_blocked'), '/api/confirm': [200, R('status_blocked_final')], '/api/status': afterConfirm('status_blocked', 'status_blocked_final')},
    [go], [
    ['status preview shown with its purpose', ({html}) => html('approval').includes('data-action="slack_status"') && html('approval').includes('not a finding alert')],
    ['exact saved status text', ({html}) => html('approval').includes(`<pre class="text" data-status-text>${escH(R('status_blocked').plan.slack_status_plan.text)}</pre>`)],
    ['outcome is blocked, not confirmed', ({html}) => html('approval').includes('<b data-outcome>blocked</b>') && html('approval').includes('no vulnerability was confirmed') && !html('approval').includes('confirmed a finding')],
    ['no Jira or finding alert offered', ({html}) => !html('approval').includes('data-action="jira"') && !html('approval').includes('data-action="slack"')],
    ['approve label', ({html}) => html('approval').includes('Approve 1 run-status notification')],
    ['council still shown as blocked', ({stage}) => stage('council') === 'blocked'],
  ]);
  await run('approved status notification is reported as sent', {...polled('status_blocked'), '/api/confirm': [200, R('status_blocked_final')], '/api/status': afterConfirm('status_blocked', 'status_blocked_final')},
    [go, t => t.execute(true)], [
    ['status sent', ({html}) => html('results').includes('data-result="slack_status"') && html('results').includes('Sent to #engineering')],
    ['no Jira result', ({html}) => !html('results').includes('data-result="jira"')],
  ]);
  await run('confirmed finding: separate escalation and status previews', polled('all_three'), [go], [
    ['escalation section', ({html}) => html('approval').includes('Escalate the confirmed finding') && html('approval').includes('data-action="jira"') && html('approval').includes('data-action="slack"')],
    ['status section', ({html}) => html('approval').includes('Run-status notification') && html('approval').includes('data-action="slack_status"')],
    ['purposes differ', ({html}) => html('approval').includes('track the finding') && html('approval').includes('alert the team about the confirmed finding') && html('approval').includes('report how this run ended')],
    ['real Jira line explained, no key yet', ({html}) => html('approval').includes('Jira: ticket not created (reason)') && !/KAN-\d/.test(html('approval'))],
    ['approve label lists all three', ({html}) => html('approval').includes('Approve 1 Jira ticket + 1 Slack message + 1 run-status notification')],
  ]);
  await run('Jira failure: status reports it, finding alert withheld, no ticket claimed', {...polled('all_three'), '/api/confirm': [502, R('all_three_jirafail')], '/api/status': afterConfirm('all_three', 'all_three_jirafail')},
    [go, t => t.execute(true)], [
    ['no Jira success', ({html}) => !/data-result="jira"[\s\S]*?data-ok="true"/.test(html('results').split('data-result="slack')[0])],
    ['status sent with failure line', ({html}) => html('results').includes('Jira: ticket not created (auth)')],
    ['finding alert withheld', ({html}) => html('results').includes('Slack notification withheld')],
    ['no ticket key anywhere', ({html}) => !/KAN-\d/.test(html('results'))],
  ]);
  await run('failed run: error shown and only a failure-status preview offered', polled('status_failed'), [go], [
    ['failure banner', ({html}) => html('banner').includes('The run failed') && html('banner').includes('missing field(s): evidence')],
    ['status preview reports failure', ({html}) => html('approval').includes('<b data-outcome>failed</b>') && html('approval').includes('The run failed before completing; no vulnerability was confirmed.')],
    ['no Jira offered', ({html}) => !html('approval').includes('data-action="jira"')],
  ]);
  await run('repository analysis: finding ticket preview and inspection scope', polled('repo_finding'), [go], [
    ['subject is a repository finding', ({html}) => html('approval').includes('Repository finding:') && html('approval').includes('not linked to a GitHub issue')],
    ['approvable', ({html}) => html('approval').includes('data-click="approve"')],
    ['scope shown, not an audit', ({html}) => html('council').includes('Repository analysis scope') && html('council').includes('script.js') && html('council').includes('not a complete security audit')],
  ]);
  await run('repository access failure is reported, no approval', polled('repo_denied'), [go], [
    ['access error in scope', ({html}) => html('council').includes('data-scope="partial"') && html('council').includes('Repository access failed: not_found: Not Found')],
    ['reviewers not run', ({html}) => (html('council').match(/data-decision="none"/g) || []).length === 3],
    ['no approval', ({hidden}) => hidden('approval')],
  ]);
  await run('confirmed finding renders real evidence and the unapplied diff', polled('informational'), [go], [
    ['evidence path and lines', ({html}) => html('finding').includes('auth.py · lines 2–3')],
    ['snippet with real line numbers', ({html}) => html('finding').includes('<i>2</i><code>' + escH('if bypass_token == "DEV-BYPASS":'))],
    ['preview-only banner', ({html}) => html('diff').includes('Preview only — not applied')],
    ['diff file header', ({html}) => html('diff').includes('<div class="diff-file">auth.py</div>')],
    ['no approval (nothing requested)', ({hidden, stage}) => hidden('approval') && stage('approval') === 'skipped'],
  ]);
  await run('cancel calls the backend and shows the cancelled plan', {...polled('bulk_cancel'), '/api/cancel': [200, R('bulk_cancel_done')], '/api/status': (n, o, st) => [200, st.cancelled ? ST('bulk_cancel_done') : ST('bulk_cancel')]},
    [go, t => t.cancelPlan()], [
    ['cancel endpoint called', ({calls}) => calls.includes('/api/cancel')],
    ['cancelled banner', ({html}) => html('banner').includes('Plan cancelled')],
    ['approval removed', ({hidden}) => hidden('approval')],
    ['approval stage skipped', ({stage}) => stage('approval') === 'skipped'],
  ]);
  await run('fail closed: plan missing saved Slack text cannot be approved', {...planned('bulk'), '/api/status': [200, ST('bulk')], '/api/result': [200, {...R('bulk'), plan: {...R('bulk').plan, slack_plan: null}}]}, [go], [
    ['approval unavailable', ({html}) => html('approval').includes('Approval unavailable') && html('approval').includes('exact saved message is missing')],
    ['no approve button', h => !approveButton(h)],
    ['cancel still offered', cancelButton],
  ]);
  await run('fail closed: ticket without review flag cannot be approved', {...planned('bulk'), '/api/status': [200, ST('bulk')], '/api/result': [200, {...R('bulk'), plan: {...bulk, jira_tickets: bulk.jira_tickets.map(({reviewed, ...rest}) => rest)}}]}, [go], [
    ['blocked', ({html}) => html('approval').includes('not for the issue the Engineering Council reviewed') && !html('approval').includes('data-click="approve"')],
  ]);
  await run('fail closed: an extra ticket for another issue cannot be approved', {...planned('bulk'), '/api/status': [200, ST('bulk')], '/api/result': [200, {...R('bulk'), plan: {...bulk, jira_tickets: [ticket, {...ticket, issue_number: 2}]}}]}, [go], [
    ['blocked', ({html}) => html('approval').includes('exactly one saved ticket') && html('approval').includes('Saved Jira ticket 2 is not for the issue') && !html('approval').includes('data-click="approve"')],
  ]);
  await run('expired approval cannot be approved and says so', polled('expired'), [go], [
    ['server marked expired', () => R('expired').plan.expired === true && R('expired').plan.approvable === false],
    ['no approve button', h => !approveButton(h)],
    ['expiry message', ({html}) => html('approval').includes('This approval has expired')],
    ['cancel still offered (server allows it)', cancelButton],
  ]);
  await run('plan approved elsewhere: no approve and no cancel', polled('approved_elsewhere'), [go], [
    ['server state executing', () => R('approved_elsewhere').plan.state === 'executing'],
    ['no approve button', h => !approveButton(h)],
    ['no cancel button', h => !cancelButton(h)],
    ['state explained', ({html}) => html('approval').includes('not awaiting approval (state: executing)')],
  ]);
  await run('409 on approve (approval already used) shows the error without crashing', {...polled('bulk'), '/api/confirm': [409, {error: 'This plan is not awaiting approval; approval was already used or never requested.'}]}, [go, t => t.execute(true)], [
    ['error shown', ({html}) => html('banner').includes('approval was already used')],
    ['idle', ({t}) => !t.S.busy],
    ['no success', noSuccess],
  ]);
  await run('410 on approve (expired on the server) shows the error', {...polled('bulk'), '/api/confirm': [410, {error: 'Plan expired; create a new plan.'}]}, [go, t => t.execute(true)], [
    ['error shown', ({html}) => html('banner').includes('Plan expired')],
    ['no success', noSuccess],
  ]);
  await run('non-JSON 500 from /api/plan is reported', {'/api/plan': [500, 'NONJSON']}, [go], [
    ['error shown', ({html}) => html('banner').includes('Request failed (500)')],
    ['idle', ({t}) => !t.S.busy],
  ]);
  await run('malformed result does not crash the page', {...planned('bulk'), '/api/status': [200, {status: 'complete', terminal: true, steps: []}], '/api/result': [200, {status: 'complete', reviews: 'x', council: 5, finding: [], actions: {jira: 'nope', slack: 7}, plan: 3, timeline: {}}]}, [go], [
    ['rendered something sane', ({t, html}) => !t.S.busy && t.S.poll === null && !html('banner').includes('could not be displayed')],
    ['no success claimed', noSuccess],
  ]);
  await run('terminal status but result not ready keeps polling until it is', {...planned('informational'), '/api/status': n => [200, n < 2 ? runningStatus : ST('informational')], '/api/result': n => n < 3 ? [404, {error: 'Result not ready.'}] : [200, R('informational')]}, [go], [
    ['result fetched after retries', ({calls}) => calls.filter(c => c === '/api/result').length === 3],
    ['rendered', ({html}) => html('finding').includes('auth.py')],
    ['polling stopped', ({t}) => t.S.poll === null],
  ]);
  await run('intermediate completed steps do not stop polling', {...planned('informational'), '/api/status': n => [200, n < 5 ? runningStatus : ST('informational')], '/api/result': [200, R('informational')]}, [go], [
    ['polled until terminal', ({calls}) => calls.filter(c => c === '/api/status').length >= 5 && calls.filter(c => c === '/api/result').length === 1],
  ]);
  await run('untrusted text is escaped and unsafe links dropped', {...polled('xss'), '/api/confirm': [200, R('xss_final')]}, [go, t => t.execute(true)], [
    ['no raw markup anywhere', ({page}) => Object.values(page.els).every(e => !/<img src=x|<script>alert/.test(e.innerHTML))],
    ['no javascript: href', ({page}) => Object.values(page.els).every(e => !/href="javascript:/i.test(e.innerHTML))],
  ]);
  await run('no private evidence fields reach the page', polled('bulk'), [go], [
    ['fixtures are client views', () => Object.values(F).every(f => !f.result.plan || Object.keys(f.result.plan).every(k => !k.startsWith('_')))],
  ]);
  console.log(failures ? `\n${failures} of ${total} scenario(s) failed` : `\nall ${total} scenarios passed`);
  process.exit(failures ? 1 : 0);
})();
